export const COURSE_TYPE_OPTIONS = [
  { label: '通识必修课', value: '通识必修课' },
  { label: '专业主干课程', value: '专业主干课程' },
  { label: '通识选修课', value: '通识选修课' },
  { label: '个性发展课', value: '个性发展课' },
  { label: '通识核心课', value: '通识核心课' },
  { label: '教师教育必修课', value: '教师教育必修课' },
  { label: '专业选修课', value: '专业选修课' },
  { label: '教师教育选修课', value: '教师教育选修课' },
  { label: '必修', value: '必修' },
  { label: '其他', value: '其他' },
  { label: '公共必修课', value: '公共必修课' },
  { label: '选修', value: '选修' },
  { label: '大学英语分级教学', value: '大学英语分级教学' },
  { label: '专业必修课', value: '专业必修课' },
  { label: '选修课', value: '选修课' },
  { label: '一级学科必修课', value: '一级学科必修课' },
  { label: '二级学科必修课', value: '二级学科必修课' },
];
