nodeLinker: hoisted
overrides:
  '@react-native-oh/react-native-harmony-cli>tar': 7.5.21
allowBuilds:
  '@react-native-oh-tpl/react-native-reanimated': true
  '@react-native-oh-tpl/react-native-svg': true
  '@react-native-ohos/react-native-inappbrowser-reborn': false
  '@shopify/react-native-skia': true
  core-js: true
  react-native-inappbrowser-reborn: false
  unrs-resolver: true
packages:
  - '.'
patchedDependencies:
  '@bacons/apple-targets@4.0.7': 'patches/@bacons__apple-targets@4.0.7.patch'
  # 'mx-jpush-expo@1.2.5': 'patches/mx-jpush-expo@1.2.5.patch'
minimumReleaseAge: 0
virtualStoreDirMaxLength: 20
