# This file was generated by RNOH autolinking.
# DO NOT modify it manually, your changes WILL be overwritten.
cmake_minimum_required(VERSION 3.5)

# @actor RNOH_APP
function(autolink_libraries target)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-oh-tpl/react-native-reanimated/src/main/cpp" ./rnoh_reanimated)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-oh-tpl/react-native-svg/src/main/cpp" ./rnoh_svg)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-oh-tpl/async-storage/src/main/cpp" ./rnoh_async_storage)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-oh-tpl/react-native-webview/src/main/cpp" ./rnoh_webview)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-oh-tpl/lottie-react-native/src/main/cpp" ./rnoh_lottie)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-oh-tpl/react-native-safe-area-context/src/main/cpp" ./rnoh_safe_area)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-oh-tpl/clipboard/src/main/cpp" ./rnoh_clipboard)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-oh-tpl/react-native-image-picker/src/main/cpp" ./rnoh_image_picker)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-oh-tpl/react-native-gesture-handler/src/main/cpp" ./rnoh_gesture_handler)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-oh-tpl/react-native-screens/src/main/cpp" ./rnoh_screens)

    set(AUTOLINKED_LIBRARIES
        rnoh_reanimated
        rnoh_svg
        rnoh_async_storage
        rnoh_webview
        rnoh_lottie
        rnoh_safe_area
        rnoh_clipboard
        rnoh_image_picker
        rnoh_gesture_handler
        rnoh_screens
    )

    foreach(lib ${AUTOLINKED_LIBRARIES})
        target_link_libraries(${target} PUBLIC ${lib})
    endforeach()
endfunction()
