/*
 * This file was generated by RNOH autolinking.
 * DO NOT modify it manually, your changes WILL be overwritten.
 */
// clang-format off
#pragma once
#include "RNOH/Package.h"
#include "ReanimatedPackage.h"
#include "SVGPackage.h"
#include "AsyncStoragePackage.h"
#include "WebViewPackage.h"
#include "LottieAnimationViewPackage.h"
#include "SafeAreaViewPackage.h"
#include "ClipboardPackage.h"
#include "RNImagePickerPackage.h"
#include "RnohReactNativeHarmonyGestureHandlerPackage.h"
#include "ScreensPackage.h"

std::vector<rnoh::Package::Shared> createRNOHPackages(const rnoh::Package::Context &ctx) {
  return {
    std::make_shared<rnoh::ReanimatedPackage>(ctx),
    std::make_shared<rnoh::SVGPackage>(ctx),
    std::make_shared<rnoh::AsyncStoragePackage>(ctx),
    std::make_shared<rnoh::WebViewPackage>(ctx),
    std::make_shared<rnoh::LottieAnimationViewPackage>(ctx),
    std::make_shared<rnoh::SafeAreaViewPackage>(ctx),
    std::make_shared<rnoh::ClipboardPackage>(ctx),
    std::make_shared<rnoh::RNImagePickerPackage>(ctx),
    std::make_shared<rnoh::RnohReactNativeHarmonyGestureHandlerPackage>(ctx),
    std::make_shared<ScreensPackage>(ctx),
  };
}
