/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/table-config/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 刷新表格配置缓存
     * @description 刷新并重新加载系统中所有支持的表格配置信息，返回当前可用的表格列表及其基本信息。通常用于配置更新后的缓存刷新。
     */
    get: operations['refresh-table-config'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/table-config/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 获取表格访问令牌
     * @description 根据表格标识符生成JWT访问令牌，用于后续的表格数据操作。该令牌包含表格配置信息和访问权限。
     */
    post: operations['get-table-token'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/tenant/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 获取租户访问令牌
     * @description 获取飞书应用的租户访问令牌，主要用于文件上传、图片处理等需要应用级权限的操作。该令牌具有较高的访问权限。
     */
    post: operations['get-tenant-token'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 系统健康检查
     * @description 检查系统运行状态，返回服务健康信息、资源使用情况等监控数据。用于负载均衡器健康检查和系统监控。
     */
    get: operations['health-check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/message/trigger': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 手动触发通知
     * @description 将 `table_identify` 写入通知通道以触发下游消费
     */
    post: operations['trigger-notification'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/openapi': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 获取 OpenAPI3 接口文档 (YAML)
     * @description 接口直接返回 docs/openapi3.yaml yaml格式的原始内容，使用BasicAuth进行验证
     */
    get: operations['get-openapi3'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sheet/photos/url': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 获取截图临时URL
     * @description 根据文件Token列表批量获取截图的临时下载URL，用于前端展示或下载图片。
     */
    get: operations['get-photo-url'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sheet/record': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 按 RecordID 查询历史反馈记录
     * @description 根据 record_id 获取单条用户反馈记录的详细内容，返回记录字段的键值对。请求中需包含合法的 table_identify，用于校验权限。
     */
    get: operations['get-table-record-by-id'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sheet/records': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 查询历史反馈记录
     * @description 根据指定的字段条件查询用户的历史反馈记录，支持分页查询。通常用于查看用户之前提交的反馈内容。
     */
    get: operations['get-table-record'];
    put?: never;
    /**
     * 创建反馈记录
     * @description 向指定的多维表格应用中添加用户反馈记录，支持文本内容、截图附件和联系方式。创建成功后会异步发送通知消息。
     */
    post: operations['create-table-record'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sheet/records/faq': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 查询FAQ问题记录
     * @description 根据学号查询用户相关的常见问题记录及其解决状态。
     */
    get: operations['get-faq-resolution-record'];
    put?: never;
    /**
     * 标记FAQ问题解决状态
     * @description 用户更新FAQ问题的解决状态，将问题标记为已解决或未解决。
     */
    post: operations['update-faq-resolution'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v2/sheet/records': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 查询用户历史反馈记录
     * @description 根据学号查询用户的历史反馈记录，支持分页查询，用于查看用户历史反馈内容。
     */
    get: operations['get-table-record-by-user'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v2/sheet/records/faq': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 查询FAQ问题记录
     * @description 根据学号查询用户相关的常见问题记录及其解决状态。
     */
    get: operations['get-faq-record'];
    put?: never;
    /**
     * 标记FAQ问题解决状态
     * @description 用户更新FAQ问题的解决状态，将问题标记为已解决或未解决。
     */
    post: operations['update-faq-resolution'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v2/sheet/sync': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 同步未同步记录
     * @description 同步指定表格下 is_synced = false 的所有记录，用于后台增量同步。
     */
    post: operations['sync-unsynced-table-records'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v2/sheet/sync/faq': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 同步FAQ问题记录
     * @description 同步某表格下的FAQ问题记录及其解决状态，用于后台增量同步或修复数据。
     */
    post: operations['sync-faq-record'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v2/sheet/sync/force': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 强制同步表格所有记录
     * @description 同步某表格下的所有记录（不区分是否已同步），用于全量重建或修复数据。慎用！！！
     */
    post: operations['force-sync-table-records'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v2/sheet/sync/user': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 强制同步用户记录
     * @description 同步指定用户在某表格下的所有记录（不区分是否已同步），用于全量重建或修复数据。
     */
    post: operations['force-sync-user-table-records'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    'domain.FAQTableRecord': {
      is_resolved?: string;
      record?: {
        [key: string]: unknown;
      };
      record_id?: string;
    };
    'domain.TableRecord': {
      record?: {
        [key: string]: unknown;
      };
      record_id?: string;
    };
    'response.Response': {
      code?: number;
      data?: unknown;
      msg?: string;
    };
    'v1.CreatTableRecordReg': {
      /** @description 联系方式，可选 */
      contact_info?: string;
      /** @description 反馈内容 */
      content: string;
      /** @description 额外记录列表，可选 */
      extra_record?: {
        [key: string]: unknown;
      };
      /** @description 图片附件 URL 列表，可选 */
      images?: string[];
      /** @description 学号，用于标记用户身份 */
      student_id: string;
      table_identify: string;
    };
    'v1.CreatTableRecordResp': {
      record_id?: string;
    };
    'v1.FAQResolutionUpdateReq': {
      is_resolved: boolean;
      record_id: string;
      resolved_field_name: string;
      table_identify: string;
      unresolved_field_name: string;
      user_id: string;
    };
    'v1.GenerateTableTokenReq': {
      /** @description 反馈表格 Identify，反馈表的唯一标识 */
      table_identify: string;
    };
    'v1.GenerateTableTokenResp': {
      access_token?: string;
    };
    'v1.GenerateTenantToken': {
      access_token?: string;
    };
    'v1.GetTableRecordByRecordIdResp': {
      record?: {
        [key: string]: unknown;
      };
    };
    'v1.GetTableRecordResp': {
      has_more?: boolean;
      page_token?: string;
      records?: components['schemas']['domain.TableRecord'][];
      total?: number;
    };
    'v1.HealthCheckResponse': {
      /** @description Process 当前进程的运行状态 */
      process?: components['schemas']['v1.ProcessStats'];
      /** @description ResponseMs 响应耗时，单位毫秒 */
      response_ms?: string;
      /** @description Status 服务状态，例如 "ok" */
      status?: string;
      /** @description System 系统资源使用情况 */
      system?: components['schemas']['v1.SystemStats'];
    };
    'v1.ProcessStats': {
      /** @description CPUPercent 进程 CPU 使用率（%） */
      cpu_percent?: string;
      /** @description GoHeapAllocMB Go 堆分配的内存（MB） */
      go_heap_alloc_mb?: string;
      /** @description Goroutines 当前运行的 goroutine 数 */
      goroutines?: string;
      /** @description MemoryRSSMB 进程常驻内存（MB） */
      memory_rss_mb?: string;
    };
    'v1.SystemStats': {
      /** @description CPUPercent CPU 使用率（%） */
      cpu_percent?: string;
      /** @description DiskPercent 磁盘使用率（%） */
      disk_percent?: string;
      /** @description DiskTotalGB 磁盘总量（GB） */
      disk_total?: string;
      /** @description DiskUsedGB 已使用磁盘（GB） */
      disk_used?: string;
      /** @description MemoryPercent 内存使用率（%） */
      memory_percent?: string;
      /** @description MemoryTotalMB 内存总量（MB） */
      memory_total?: string;
      /** @description MemoryUsedMB 已使用内存（MB） */
      memory_used?: string;
    };
    'v1.TriggerNotificationReq': {
      /** @description 反馈表格 Identify，反馈表的唯一标识 */
      table_identify: string;
    };
    'v2.FAQResolutionUpdateReq': {
      is_resolved: boolean;
      record_id: string;
      table_identify: string;
      user_id: string;
    };
    'v2.ForceSyncTableRecordsReq': {
      table_identify: string;
    };
    'v2.ForceSyncTableRecordsResp': {
      /** @description 队列是否已满 */
      queue_full?: boolean;
      /** @description 成功投递到队列的记录 ID */
      record_ids?: string[];
      /** @description 本次尝试同步的总记录数 */
      total?: number;
    };
    'v2.ForceSyncUserTableRecordsReq': {
      student_id: string;
      table_identify: string;
    };
    'v2.ForceSyncUserTableRecordsResp': {
      /** @description 队列是否已满 */
      queue_full?: boolean;
      /** @description 成功投递到队列的记录 ID */
      record_ids?: string[];
      /** @description 本次尝试同步的总记录数 */
      total?: number;
    };
    'v2.GetTableRecordByRecordIdResp': {
      records?: components['schemas']['domain.FAQTableRecord'][];
    };
    'v2.GetTableRecordResp': {
      has_more?: boolean;
      page_token?: string;
      records?: components['schemas']['domain.TableRecord'][];
    };
    'v2.SyncFaqRecordReq': {
      table_identify: string;
    };
    'v2.SyncUnsyncedTableRecordsReq': {
      table_identify: string;
    };
    'v2.SyncUnsyncedTableRecordsResp': {
      /** @description 队列是否已满 */
      queue_full?: boolean;
      /** @description 成功投递到队列的记录 ID */
      record_ids?: string[];
      /** @description 本次尝试同步的总记录数 */
      total?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'refresh-table-config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 成功返回目前支持索引的表格的公开配置 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'get-table-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 获取Token请求参数 */
    requestBody: {
      content: {
        'application/json': components['schemas']['v1.GenerateTableTokenReq'];
      };
    };
    responses: {
      /** @description 成功返回 JWT 令牌 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'] & {
            data?: components['schemas']['v1.GenerateTableTokenResp'];
          };
        };
      };
      /** @description 请求参数错误 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'get-tenant-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 成功返回 JWT 令牌 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'] & {
            data?: components['schemas']['v1.GenerateTenantToken'];
          };
        };
      };
      /** @description 请求参数错误 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'health-check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 系统运行正常，返回健康检查详情 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'] & {
            data?: components['schemas']['v1.HealthCheckResponse'];
          };
        };
      };
      /** @description 系统异常或部分服务不可用 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'] & {
            data?: string;
          };
        };
      };
    };
  };
  'trigger-notification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 触发通知请求参数 */
    requestBody: {
      content: {
        'application/json': components['schemas']['v1.TriggerNotificationReq'];
      };
    };
    responses: {
      /** @description 触发成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 请求参数错误 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'get-openapi3': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 成功返回 OpenAPI3 文档内容 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/x-yaml': string;
        };
      };
      /** @description 未授权，BasicAuth 验证失败 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/x-yaml': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/x-yaml': components['schemas']['response.Response'];
        };
      };
    };
  };
  'get-photo-url': {
    parameters: {
      query: {
        /** @description 附件 token */
        file_tokens: string[];
      };
      header: {
        /** @description Bearer Token */
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 成功返回临时URL信息 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 请求参数错误或飞书接口调用失败 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'get-table-record-by-id': {
    parameters: {
      query: {
        /** @description 记录 ID */
        record_id: string;
        table_identify: string;
      };
      header: {
        /** @description Bearer Token */
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 成功返回查询结果 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'] & {
            data?: components['schemas']['v1.GetTableRecordByRecordIdResp'];
          };
        };
      };
      /** @description 请求参数错误或飞书接口调用失败 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'get-table-record': {
    parameters: {
      query: {
        /** @description 用于查询记录的关键值，一般使用学号的字段名 */
        key_field: string;
        /** @description 用于查询记录的关键值，一般使用学号的字段值 */
        key_value: string;
        /** @description 分页参数,第一次不需要 */
        page_token?: string;
        /** @description 需要查询的字段名 */
        record_names: string[];
        table_identify: string;
      };
      header: {
        /** @description Bearer Token */
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 成功返回查询结果 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'] & {
            data?: components['schemas']['v1.GetTableRecordResp'];
          };
        };
      };
      /** @description 请求参数错误或飞书接口调用失败 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'create-table-record': {
    parameters: {
      query?: never;
      header: {
        /** @description Bearer Token */
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    /** @description 新增记录请求参数 */
    requestBody: {
      content: {
        'application/json': components['schemas']['v1.CreatTableRecordReg'];
      };
    };
    responses: {
      /** @description 成功返回创建记录结果 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'] & {
            data?: components['schemas']['v1.CreatTableRecordResp'];
          };
        };
      };
      /** @description 请求参数错误或飞书接口调用失败 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'get-faq-resolution-record': {
    parameters: {
      query: {
        /** @description 需要查询的字段名 */
        record_names: string[];
        /** @description 学号，用于标记用户身份 */
        student_id: string;
        table_identify: string;
      };
      header: {
        /** @description Bearer Token */
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 成功返回单条记录的字段键值对 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'] & {
            data?: components['schemas']['v1.GetTableRecordByRecordIdResp'];
          };
        };
      };
      /** @description 请求参数错误或飞书接口调用失败 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'update-faq-resolution': {
    parameters: {
      query?: never;
      header: {
        /** @description Bearer Token */
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    /** @description 更新FAQ解决状态请求参数 */
    requestBody: {
      content: {
        'application/json': components['schemas']['v1.FAQResolutionUpdateReq'];
      };
    };
    responses: {
      /** @description 成功更新FAQ解决状态 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 请求参数错误或飞书接口调用失败 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'get-table-record-by-user': {
    parameters: {
      query: {
        limit_size?: number;
        /** @description 分页参数,第一次不需要 */
        page_token?: string;
        /** @description 学号，用于标记用户身份 */
        student_id: string;
        table_identify: string;
      };
      header: {
        /** @description Bearer Token */
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 成功返回查询结果 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'] & {
            data?: components['schemas']['v2.GetTableRecordResp'];
          };
        };
      };
      /** @description 请求参数错误 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'get-faq-record': {
    parameters: {
      query: {
        /** @description 学号，用于标记用户身份 */
        student_id: string;
        table_identify: string;
      };
      header: {
        /** @description Bearer Token */
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 成功返回单条记录的字段键值对 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'] & {
            data?: components['schemas']['v2.GetTableRecordByRecordIdResp'];
          };
        };
      };
      /** @description 请求参数错误或飞书接口调用失败 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'update-faq-resolution': {
    parameters: {
      query?: never;
      header: {
        /** @description Bearer Token */
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    /** @description 更新FAQ解决状态请求参数 */
    requestBody: {
      content: {
        'application/json': components['schemas']['v2.FAQResolutionUpdateReq'];
      };
    };
    responses: {
      /** @description 成功更新FAQ解决状态 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 请求参数错误或飞书接口调用失败 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'sync-unsynced-table-records': {
    parameters: {
      query?: never;
      header: {
        /** @description Bearer Token */
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    /** @description 同步请求参数 */
    requestBody: {
      content: {
        'application/json': components['schemas']['v2.SyncUnsyncedTableRecordsReq'];
      };
    };
    responses: {
      /** @description 同步成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'] & {
            data?: components['schemas']['v2.SyncUnsyncedTableRecordsResp'];
          };
        };
      };
      /** @description 请求参数错误 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'sync-faq-record': {
    parameters: {
      query?: never;
      header: {
        /** @description Bearer Token */
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    /** @description 同步FAQ记录请求参数 */
    requestBody: {
      content: {
        'application/json': components['schemas']['v2.SyncFaqRecordReq'];
      };
    };
    responses: {
      /** @description 成功同步FAQ记录 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'force-sync-table-records': {
    parameters: {
      query?: never;
      header: {
        /** @description Bearer Token */
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    /** @description 强制同步请求参数 */
    requestBody: {
      content: {
        'application/json': components['schemas']['v2.ForceSyncTableRecordsReq'];
      };
    };
    responses: {
      /** @description 同步成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'] & {
            data?: components['schemas']['v2.ForceSyncTableRecordsResp'];
          };
        };
      };
      /** @description 请求参数错误 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
  'force-sync-user-table-records': {
    parameters: {
      query?: never;
      header: {
        /** @description Bearer Token */
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    /** @description 强制同步请求参数 */
    requestBody: {
      content: {
        'application/json': components['schemas']['v2.ForceSyncUserTableRecordsReq'];
      };
    };
    responses: {
      /** @description 同步成功 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'] & {
            data?: components['schemas']['v2.ForceSyncUserTableRecordsResp'];
          };
        };
      };
      /** @description 请求参数错误 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['response.Response'];
        };
      };
    };
  };
}
