name: Build Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '9.14.4'

      - name: Install dependencies
        run: pnpm install

      - name: Build and Test
        run: pnpm run build
        continue-on-error: false

      - name: Check if PR should be blocked
        if: github.event_name == 'pull_request'
        run: |
          echo "If the 'Build and Test' step fails, the PR will be blocked from merging."