name: Require Specific Reviewers Based on File Changes

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v33
        with:
          files: '**'

      - name: Determine required reviewers
        id: determine-reviewers
        run: |
          declare -A REVIEWERS_MAP
          REVIEWERS_MAP["app"]="BlackishGreen33 konodioda727 Old-Second"
          REVIEWERS_MAP["module"]="BlackishGreen33 konodioda727 Old-Second"
          REVIEWERS_MAP["components"]="BlackishGreen33 konodioda727 Old-Second"
          REVIEWERS_MAP["hooks"]="BlackishGreen33 konodioda727 Old-Second"
          REVIEWERS_MAP["utils"]="BlackishGreen33 konodioda727 Old-Second"

          CHANGED_FILES=${{ steps.changed-files.outputs.all_changed_files }}
          REQUIRED_REVIEWERS=()

          for FILE in $CHANGED_FILES; do
            for FOLDER in "${!REVIEWERS_MAP[@]}"; do
              if [[ "$FILE" == "$FOLDER/"* ]]; then
                REVIEWERS=${REVIEWERS_MAP[$FOLDER]}
                for REVIEWER in $REVIEWERS; do
                  if [[ ! " ${REQUIRED_REVIEWERS[@]} " =~ " ${REVIEWER} " ]]; then
                    REQUIRED_REVIEWERS+=("$REVIEWER")
                  fi
                done
              fi
            done
          done

          echo "REQUIRED_REVIEWERS=${REQUIRED_REVIEWERS[*]}" >> $GITHUB_ENV
          echo "Required reviewers: ${REQUIRED_REVIEWERS[*]}"
        shell: bash

      - name: Check PR reviews
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          APPROVED_REVIEWERS=$(gh pr list --state open --json number,reviewDecision --jq '.[] | select(.number == $PR_NUMBER) | .reviewDecision' -- PR_NUMBER=${PR_NUMBER})

          REQUIRED_REVIEWERS=${{ env.REQUIRED_REVIEWERS }}
          APPROVED=false

          for REVIEWER in ${REQUIRED_REVIEWERS}; do
            if [[ "$APPROVED_REVIEWERS" == *"APPROVED"* ]]; then
              APPROVED=true
              break
            fi
          done

          if [ "$APPROVED" = false ]; then
            echo "Error: PR must be approved by at least one of the required reviewers: ${REQUIRED_REVIEWERS[*]}"
            exit 1
          else
            echo "PR is approved by at least one required reviewer. Proceeding with merge."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash