name: iOS Build Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-ios:
        runs-on: macos-14
        timeout-minutes: 60

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Set up pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 9.14.4

            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Cache CocoaPods
              uses: actions/cache@v3
              with:
                  path: ios/Pods
                  key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-pods-

            # ⚡️ 仅首次预构建 Expo iOS 项目
            - name: Prebuild iOS project
              run: pnpm expo prebuild --platform ios --non-interactive --no-install
              env:
                  EXPO_NO_DOCTOR: 1

            - name: Install CocoaPods
              run: |
                  cd ios
                  pod install

            - name: Build iOS app
              run: |
                  cd ios
                  xcodebuild \
                    -workspace ccnubox.xcworkspace \
                    -scheme ccnubox \
                    -configuration Release \
                    -sdk iphonesimulator \
                    -derivedDataPath build
              env:
                  CI: true

            - name: Notify on failure
              if: failure()
              run: echo "❌ iOS build failed. Please check the logs above."
