name: Test Update

on:
  push:
    branches:
      - main
    paths:
      - "src/assets/data/updateInfo.json"
  workflow_dispatch:

jobs:
  eas-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Install dependencies
        run: pnpm install

      - name: Run EAS Update
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          pnpx eas-cli update --branch test --message "${{ github.event.head_commit.message }}"
